# Onboarding

----------

## First Steps

If you are a new member of the BAB Lab, there are a few basic things you will want to set up before or on your first day. 

**Here are some tips:**

 1. Read the [Lab Manual](https://bab-lab.github.io/lab_manual/)

 2. Ask the lab manager to be added to the following
- [Slack](https://slack.com/) (download the desktop and mobile [apps](https://slack.com/downloads/mac))
- [Trello](https://trello.com/emilyanntowner/boards) (download the desktop and mobile [apps](https://trello.com/en-US/platforms) - watch this [tutorial](https://www.youtube.com/watch?v=_Ry-SnJygy8&feature=youtu.be))
- Box
- Google calendars
- Email list
- Dropbox Paper

3. Send (via Slack) the lab manager your information including your
- Preferred name
- Preferred email
- Phone number
- Photo
- Brief bio for the lab website

 4. Complete the onboarding process for your position below

----------

## Onboarding - Staff Research Associate

1. Submit to Bridget
    - Signed employment contract
2. Contact HR
    - Human Resources Coordinator
    - 1283A Franz Hall
    - <a href="tel:3102069720">(310) 206-9720</a>
3. Submit to HR
    - [Union overtime/comp form](https://ucla.app.box.com/s/z58tkq6l13qwl0zw5gtqhdxq0cne1wcu)
    - [Personal data form](https://ucla.app.box.com/s/7jmouwl8fbp5039qq4tfmreo5r5ydmjq)
    - [Background check authorization form](https://ucla.app.box.com/s/tothrcm0zcz50hj829bkcj1idclcudzr)
4. Schedule with HR
    - Background check phone call
    - Hiring meeting
    - Bring employment verification [documents](https://ucla.app.box.com/s/iwguajwkedo2zf2lfr5ie3z5tc4vnz7m) to meeting (i.e. passport)
    - Sign [state oath of allegiance/patent policy/patent acknowledgment](https://ucnet.universityofcalifornia.edu/forms/pdf/upay-585.pdf) (in person)
5. Pick-up
    - Location: Psychology Main Office (1285 Psychology Building – See Tyler Tuione)
        - Parking permits
6. Respond
    - To the tracker I-9 email on or before your first day of work
7. Create (once you have your employee ID)
    - Create a [UCLA logon ID](https://accounts.iam.ucla.edu/#/)
    - Create a [UCPath account](https://idpproxy-ucpath.universityofcalifornia.edu/simplesaml/module.php/ucpathdiscovery/disco.php?entityID=https://ucpath.universityofcalifornia.edu&return=https://idpproxy-ucpath.universityofcalifornia.edu/simplesaml/module.php/saml/sp/discoresp.php?AuthID=_6a3d8a7c8144ccec21e8fff0206d805c7b4d0beb08%253Ahttps%253A%252F%252Fidpproxy-ucpath.universityofcalifornia.edu%252Fsimplesaml%252Fsaml2%252Fidp%252FSSOService.php%253Fspentityid%253Dhttps%25253A%25252F%25252Fucpath.universityofcalifornia.edu%25253A443%25252Fsimplesaml%25252Fmodule.php%25252Fsaml%25252Fsp%25252Fmetadata.php%25252Fdefault-sp%2526cookieTime%253D1563390873%2526RelayState%253Dhttps%25253A%25252F%25252Fucpath.universityofcalifornia.edu%25252Fsaml_login&returnIDParam=idpentityid) (payroll, benefits, etc.)
    - Create an At Your Service Online ([AYSO](https://atyourserviceonline.ucop.edu/ayso/)) account (retirement)
8. Visit (once you have your employee ID)
    - Location: UCLA BruinCard Center (Kerckhoff Hall, Room 123)
        - Bring ID and completed [form](https://secure.bruincard.ucla.edu/BCW/BruinCard_Web/Docs/BC%20Terms%20%20Signature%2006.pdf)
9. Complete (once you have your UCLA logon ID)
    - Sign-up and complete the required employee training [courses](https://ucla.app.box.com/s/mizhokn39tq7z6odvnvutvaoko11n823)
    - Sign-up and attend [orientation](https://www.chr.ucla.edu/training-and-development/new-employee-orientation)
    - Upload orientation training certificates to Box (BABLAB/Lab/Training)
10. Select
    - Health insurance plan (within 30 days)
Retirement plan (within 90 days)
Union membership requires pension plan
11. Pritzker Access
    - Email Tyler Tuione – tuione@psych.ucla.edu
    - Include your name and Bruincard # to be granted weekend swipe card access as well as B and C level access for freezer storage
    - The swipe access reader is located on the right hand side of door to the right courtyard of the tower entrance.
12. IRB Trainings
    - Create a [UCLA SSO for CITI Program](http://ora.research.ucla.edu/OHRPP/Documents/Education/SSO_CITI_New_Acct.pdf)
    - Add and complete the following courses:
        - Human Research – Social & Behavioral Researchers & Staff
        - Human Research- Biomedical Researchers & Staff
        - UCLA HIPAA
    - Add certificates to the training folder on Box (BABLAB/Lab/Training)
    - Get a WebIRB account
        - Email your faculty sponsor/advisor the following information:
            - Your UCLA Logon ID – (Verify your [UCLA Logon ID](https://accounts.iam.ucla.edu/lookup))
            - Your UCLA UID # (9-digit)
            - Your full name
                - First
                - Middle
                - Last
            - Your email address
            - Your department and division
        - Bridget to email this information to webIRBHelp@research.ucla.edu to request the account.
        - Ask the lab manager to be added to all IRB protocols
13. IBC Trainings
    - Sign up for the following courses via UCLA [WorkSafe](https://worksafe.ucla.edu/Ability/Programs/Standard/Control/elmLearner.wml?PortalID=LearnerWeb)
        - NIH Guidelines for UCLA Researchers IBC Compliance Training (online)
        - Laboratory Safety Fundamentals (online)
        - Blood-borne Pathogens Training (online)
        - Medical Waste Management (online)
        - Biosafety ABC’s – Biosafety Level 2 Training (in-person)
        - Biosafety Cabinet (online)
    - Add certificates to your user folder on Box (BABLAB/Lab/Training)
    - Record completion for [HPL](https://docs.google.com/document/d/1hCYg4hYJ7wi4nsLl1vDs1a-7Of3Tnzvocx58bdcj2cc/edit)
    - Submit certificates to Arielle Radin (radina02@g.ucla.edu) at HPL
    - Read the [Lab Specific Biosafety Manual](https://ucla.box.com/s/igqe24fbhh6cjqqbysdjye482tuw0axd) and sign off
    - Complete Lab Specific Training and sign off
        - This must be updated annually
    - Get vaccinations (suggested)
        - Visit OHF at 67-120 CHS x56771
        - Recommended vaccines
            - Hepatitis B
            - Flu (Influenza)
            - MMR (Measles, Mumps & Rubella)
            - Varicella (Chickenpox)
            - Tdap (Tetanus, Diptheria, Pertussis)
            - Meningococcal
14. REDCap
    - Complete and send REDCap access form to Martin Lai (mylai@mednet.ucla.edu) (BABLAB/Lab/Lab_protocols/REDCap/Access/Template/)
15. Website admin access 
    - Contact Jun Wan (jwan@psych.ucla.edu) for access to the [life sciences Wordpress multisite server](https://sites.lifesci.ucla.edu/)
16. MRI Trainings
    - TBD 
17. Department of Psychology Printing Acess
    - [Login](https://support.lifesci.ucla.edu/hc/en-us) (upper right hand corner)
    - Click submit a request
    - Inquire about gaining printer access- include your UID number and email
    - Access printing at Franz Hall 
    - [Instructions](https://ucla.app.box.com/s/db0zzvgrydw1yz99yo1nlooq1j4n7jos) - sending print jobs via email 
18. [Departmental Email Distributions](https://ucla.app.box.com/v/Psych-Directory-List)

<h4>Important links:</h4>

- [UCLA time reporting system](24https://uctrs.it.ucla.edu/)

<h4>Review:</h4>

- [Getting started at UCLA](https://www.chr.ucla.edu/new-employee/getting-started)
- [Welcome Kit](https://ucnet.universityofcalifornia.edu/forms/pdf/welcome-kit.pdf)
- [How-to access UCPath portal](https://www.centralresourceunit.ucla.edu/s/)
- [Workers’ Comp
Pamphlet](https://ucla.app.box.com/s/jyzoag8v9qw6katuvgegjil8an2tsx2j)
- [When an injury occurs](https://ucla.app.box.com/s/nua4ypfpjlt1226fusney4zyvo6qzzhj)
- [Substance Abuse Brochure](https://ucla.app.box.com/s/qrj4j7bnca1r8fy9n1bdfdf6orf1g0dq)

----------

## Onboarding - Volunteer Research Assistant (UCLA Students)

1. Website
   - Please send us your preferred name, photo, and a brief bio for the lab website
2. IRB Trainings- IMPORTANT
   - No one can access our Box or data until all IRB trainings are complete!
   - Create a [UCLA SSO](https://ora.research.ucla.edu/OHRPP/Documents/Education/SSO_CITI_New_Acct.pdf) for CITI Program or [login](https://www.research.ucla.edu/CITIProgram/) through UCLA
   - Add and complete the following courses:
       - UCLA HIPAA
       - Human Research - Social & Behavioral Researchers & Staff
       - Human Research - Biomedical Researchers & Staff
   - Slack message these certificates to the lab manager
   - Ask to be added to any relevant IRB protocols
3. Accessing Trello
   - [Trello](https://trello.com) is our task management software!
      - Download the desktop an mobile [apps](https://trello.com/en-US/platforms)
      - Please watch this [tutorial](https://youtu.be/_Ry-SnJygy8)
4. HR Requirements (not necessary for UCLA students)
   - Lab Manager must consult with Bridget prior to hiring. Background checks must be run for all volunteers who are not UCLA students (~$50 each). Unless otherwise specified, the Lab Manager should refer to the RA application pool within UCLA students.
   - Please print, read, and complete the forms located in the Dropbox/BAB/Lab/Lab_protocols/RA_hiring/Forms
   - Each form MUST be completed thoroughly. Some persons omit information such as social security information, but if any area is left vacant, we cannot accept the forms and the volunteer will not be able to work on the UCLA campus. There must be a clear start date and a clear end date. The majority of the forms are filled out by the volunteer, but there are a few areas where the UCLA professor whose lab is overseeing the volunteer must sign and date as well. 
   - The volunteer may not work on the UCLA campus until all forms are filled out, signed, and submitted back to HR.
5. Franz Access
   - Email the lab manager to request weekend access if you will be running participants on the evenings/weekends
     - Student volunteers: Include your name and Bruincard #
     - Non-student volunteers: We will determine if you are eligible for an access card.
   - The swipe access reader is located on the right hand side of door to the right courtyard of the tower entrance.
6. BMC Requirements
   - TBD

## Onboarding - Postdoctoral Scholar

----------

## Onboarding - Graduate Student

For lab manager to do:

1. Add new graduate student to:
  - BABLab calendars
  - GitHub
  - Slack workspace
  - Google group
  - Box 
  - Relevant REDcap projects
  - OSF
  - Trello
  - IRB(s)

For graduate student to do:

1. Make your UCLA ID (instructions sent when accept admissions offer)
2. Submit your statement of intent to register (SIR) and statement of legal residence (SLR) forms
3. Check your UCLA email regularly and add it to your mail app 
4. Once you are given access to Box through UCLA (you will receive an email notification), [download box drive](https://www.box.com/resources/downloads) and get set up
5. Once lab manager requests that you be added to REDcap and you get an email about it, fill out the access form and go through the steps to set up an account
6. Set up [access](https://www.library.ucla.edu/use/computers-computing-services/connect-campus) to papers & databases off-campus through UCLA.
7. Watch the BABLab Trello how-to [video](https://www.youtube.com/watch?v=_Ry-SnJygy8&feature=youtu.be&ab_channel=BABLab) and download [Trello](https://trello.com/en-US/platforms). 
8. Make an account on [OSF](https://accounts.osf.io/login?service=https://osf.io/myprojects/)
9. Do the following IRB trainings:
  - These are done on the [CITI program](https://www.research.ucla.edu/CITIProgram/) by creating a [UCLA SSO](https://ora.research.ucla.edu/OHRPP/Documents/Education/SSO_CITI_New_Acct.pdf), then add and complete the following
  - UCLA HIPAA
  - Human Research - Social & Behavioral Researchers & Staff
  - Human Research- Biomedical Researchers & Staff
  - Once you have done them, please slack the lab manager the certificates for our records
10. Get an account on the IRB site (required before you can be added to IRBs!)
  - Email Bridget the following info so that she can get you an account:
    - Your UCLA logon ID
    - Your UCLA ID # (9 digits)
    - Your full name (first, middle, last)
    - Your email address
    - Your department and division
11. Train to collect data for whichever large study is currently going on in the lab
  - Meet with lab manager & Bridget to discuss study
  - Read study wiki & data collection protocols
  - Meet with lab manager to address questions regarding protocols
  - Shadow several data collection sessions
  - Do a pilot session & pass
  - Run your first session reverse-shadowed by someone who is trained
12. Get your UCLA BruinCard
  - Submit a message to the BruinCard center to request a new bruincard
    - Go to my.ucla.edu and log in
    - Click the yellow “Need help?” in the top right corner, then click on “message center”
    - Submit a question to the BruinCard center, with the topic “requesting new bruincard”
  - In your message, include the following info:
    - UCLA ID number, contact phone, contact email, department, requested pickup date and time (Monday, Wednesday, Friday 10am-2pm), have you had a previous BruinCard? Was your online photo submission approved? (you will be prompted to upload a photo in the admissions process, if that was approved you can say yes)
    - Attach a scanned copy of your govt issued photo ID
  - Go pick up your card at the specified location at the time you were scheduled for
    - Make sure to bring the same photo ID you provided a copy of!
  - Once you have your bruincard, let the lab manager know so that they can request lab access for you!
13. Learn how to make IRB amendments and navigate the UCLA IRB portal
  - If you haven't already requested an IRB account, do that ASAP
  - Once you have an account, meet with the lab manager to go over how to navigate the UCLA [IRB site](https://webirb.research.ucla.edu/WEBIRB/Rooms/DisplayPages/LayoutInitial?Container=com.webridge.entity.Entity[OID[AC482809EC03C442A46F2C8EEC4D75D3]])
