--- 
title: "Brain and Body Lab"
# author: "Emily Towner"
# date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "These are the notes, logs, and protocols for the Brain and Body Lab at UCLA"
---

# Introduction

----------


<h1>Welcome to the BABLab Wiki!</h1>

In the <b>Brain and Body Lab</b> we are interested in how early experiences influence interactions between the brain and body, contributing to mental and physical health. We hope to use this information to improve the wellbeing of children, adolescents, and adults across the world. In other words, in the BABLab, we aim to do good science that makes a difference to people’s lives, today and tomorrow.

The BABLab is directed by Dr. Bridget Callaghan, Assistant Professor of Psychology at UCLA.

**Current Projects:**

 - [Mind, Brain, Body (MBB)](https://bab-lab.github.io/mind_brain_body/)
 - [EGG and Emotionality (EGG)](https://osf.io/nf2bv/)
 - Transfer Mental Health

<hr>

## Finding the Lab

We're located in the Psychology Department at UCLA! <br>
5581 Pritzker Hall <br>
This is in the tower building, 5th floor.

<hr>

## Contact Info

If you have any questions about the lab please contact the lab's managers.

Emily Towner - [emilytowner@ucla.edu](mailto:emilytowner@ucla.edu). <br>
Kristen Chu - [kristenchu@g.ucla.edu](mailto:kristenchu@g.ucla.edu)

Alternatively, you can reach out to our lab email, [bablab.ucla@gmail.com](mailto:bablab.ucla@gmail.com)

<hr>

## Other Information

Feel free to contribute any relevant sections or information - best lunch spots on campus, tips and tricks, or anything else helpful to your fellow lab members!

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
